# docker-compose.yml

version: '3.8'

services:
  minio: 
    image: minio/minio  # Imagem oficial do MinIO
    container_name: minio
    ports:
      - "9000:9000"  # Porta da API do MinIO
      - "9001:9001"  # Porta do Console de Administração
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ./dados_minio:/data